---
- hosts: all
  become: yes
  become_user: root
  tasks:
    - name: Install nginx and certbot
      ansible.builtin.apt:
        pkg:
        - nginx
        - certbot
        - python-simplejson
        - curl
        - rsync
        update_cache: yes
        
        


#      - name: add apt key for nodesource
#       apt_key: url=https://deb.nodesource.com/gpgkey/nodesource.gpg.key

#     - name: add repo for nodesource
#       apt_repository:
#             repo: 'deb https://deb.nodesource.com/node_0.10 {{ ansible_distribution_release }} main'
#             update_cache: yes

#     - name: install nodejs
#       apt: name=nodejs

#     - name: install NPM
#          shell: npm i
#          args:
#            chdir: /home/ubuntu

#     - name: Install PM2
#       npm:
#         name: pm2
#         global: yes
