---

- raw: apt-get install -y python-simplejson

- name: Upgrade system
  apt: upgrade=dist update_cache=yes

- name: Install nginx
  apt: name=nginx state=latest

- name: Remove default nginx config
  file: name=/etc/nginx/sites-enabled/default state=absent

- name: Install system nginx config
  template:
    src: templates/nginx.conf.j2
    dest: /etc/nginx/nginx.conf

- name: Install nginx site for letsencrypt requests
  template:
    src: templates/nginx-http.j2
    dest: /etc/nginx/sites-enabled/http
  notify:
  - reload nginx
