---
- name: Remove default nginx config
  file: name=/etc/nginx/sites-enabled/default state=absent

- name: Install system nginx config
  template:
    src: templates/nginx.conf.j2
    dest: /etc/nginx/nginx.conf

- name:  Synchronization certs using rsync 
  raw: rsync -avz rsync://96.126.70.174/le /etc/letsencrypt/ --delete

- name: Generate dhparams
  shell: openssl dhparam -out /etc/nginx/dhparams.pem 2048
  args:
    creates: /etc/nginx/dhparams.pem
    
- name: Install nginx site for letsencrypt requests
  template:
   src: templates/nginx-http.j2
   dest: /etc/nginx/sites-enabled/http
  notify:
  - reload nginx
