---

- name:  Synchronization certs using rsync 
  ansible.posix.synchronize:
    src: rsync://96.126.70.174/le/
    dest: /etc/letsencrypt/live/
    delete: yes
    recursive: yes
  delegate_to: "{{ inventory_hostname }}"

- name: Generate dhparams
  shell: openssl dhparam -out /etc/nginx/dhparams.pem 2048
  args:
    creates: /etc/nginx/dhparams.pem

- name: Install nginx site for specified site
  template:
    src: templates/nginx-subdomain.j2
    dest: /etc/nginx/sites-enabled/{{ item.subdomain }}.{{ domain }}
  notify:
    - reload nginx
  with_items: "{{ subdomains }}"
