---

- name:  Synchronization certs using rsync 
  raw: rsync -avz rsync://96.126.70.174/le /etc/letsencrypt/live/ --delete

- name: Generate dhparams
  shell: openssl dhparam -out /etc/nginx/dhparams.pem 2048
  args:
    creates: /etc/nginx/dhparams.pem

- name: Install nginx site for specified site
  template:
    src: templates/nginx-subdomain.j2
    dest: /etc/nginx/sites-enabled/{{ item.subdomain }}.{{ domain }}
  notify:
    - reload nginx
  with_items: "{{ subdomains }}"
